### ISSUE TITLE
fail to run fritz image segmentation on google AI platform?

### ISSUE THREAD

**Issue by randylu** [fritzlabs/fritz-models#59]
When I submit and train "fritz image segmentation" on google AI platform, it fails.
  I think it's something about the keras version, but don't know how to fix it.
  Additionally, I use the tensorflow 1.9, keras 2.2.4(the default version in "fritz image segmentation").
  The error log is as follows:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/image_segmentation/train.py", line 395, in <module>
    train(sys.argv[1:])
  File "/root/.local/lib/python2.7/site-packages/image_segmentation/train.py", line 358, in train
    callbacks=callbacks,
  File "/root/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1010, in fit
    self._make_train_function()
  File "/root/.local/lib/python2.7/site-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "/root/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/keras/optimizers.py", line 505, in get_updates
    self.updates.append(K.update(m, m_t))
  File "/root/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 973, in update
    return tf.assign(x, new_x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 220, in assign
    return ref.assign(value, name=name)
AttributeError: 'Tensor' object has no attribute 'assign'

**Comment by jamesonthecrow** [comment]
You'll need to upgrade your tensorflow and python versions to tensorflow 1.13.1 and python 3.5

**Comment by randylu** [comment]
@jamesonthecrow , thanks for your advice.
But when I change tensorflow and python versions to tensorflow 1.13.1 and python 3.5, the same error when running on google AI platform.

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/image_segmentation/train.py", line 395, in <module>
    train(sys.argv[1:])
  File "/root/.local/lib/python3.5/site-packages/image_segmentation/train.py", line 358, in train
    callbacks=callbacks,
  File "/root/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1010, in fit
    self._make_train_function()
  File "/root/.local/lib/python3.5/site-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "/root/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.5/site-packages/keras/optimizers.py", line 505, in get_updates
    self.updates.append(K.update(m, m_t))
  File "/root/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 973, in update
    return tf.assign(x, new_x)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 224, in assign
    return ref.assign(value, name=name)
AttributeError: 'Tensor' object has no attribute 'assign'
